### ISSUE TITLE
review

### ISSUE THREAD

**Issue by flrngel** [azamatkhid/densenet-pytorch#2]
1. Dataset as an argument
- model is only for `CIFAR` dataset. below might be help.
```python
def DatasetWrapper(_class):
    class Dataset(_class):
        def __init__(self, root, train=None, transform=None, target_transform=None, download=False):
            super(Dataset, self).__init__(root, train=train, transform=transform, target_transform=target_transform, download=download)
        def __getitem__(self, index):
            img, target = self.data[index], int(self.targets[index])
            img = Image.fromarray(img.numpy(), mode='L')
            img_transform = self.transform(img)
            img_transform2 = self.transform(img)
            img = torch.cat([img_transform, img_transform2], dim=0)
            return img, target, index

    return Dataset

dataset_wrapper = DatasetWrapper(getattr(datasets, args.dataset))
dataset = dataset_wrapper(
    args.datasets_path,
    download=args.download_dataset,
    transform=transform
)

data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=args.batch_size,
    shuffle=args.shuffle,
    num_workers=args.nThreads,
)
```
(modified from https://github.com/HobbitLong/CMC/blob/master/train_moco_ins.py)

2. Conventions 
- `a=b` => `a = b`. Use space between all operations. Hard to recognize.
- `a,b` => `a, b`
3. things like `get_original_cwd` should be done on initializing process (use Hydra)
4. hydra imported twice (https://github.com/azamatkhid/densenet-pytorch/blob/master/model.py#L124)
5. your `Model` class means Application. `DenseNet` is Model.

**Comment by flrngel** [comment]
`class DenseNet` is fine. For example, we can just copy without changing it's classname.

**Comment by azamatkhid** [comment]
Fixed: ```class Model``` -> ```class DenseNet```

**Comment by azamatkhid** [comment]
@flrngel i re-structured code in order to use best of hydra. Thanks to comment by omegaconf & hydra author. 

* removed unnecessary ```main.py```. 
* in ```class Application``` add method ```build()``` to initialize the network itself, this makes easier to inherit ```Application``` into ```class DenseNet_official``` in the ```ref_app.py``` module (previously ```reference_model.py```)
* removed unnecessary imports in ```ref_app.py```
* fix minor bugs

**Comment by azamatkhid** [comment]
@flrngel plz let me know if you think review is done, so i will close an issue. TIA)
